# Generated by Django 4.2.4 on 2023-09-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
