# Generated by Django 4.2.4 on 2023-09-08 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_tweet_likes_tweet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_likes',
            name='curr_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet_likes',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tweet'),
        ),
    ]
