# Generated by Django 4.2.4 on 2023-09-08 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_tweet_likes_curr_user_alter_tweet_likes_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_Retweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curr_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(related_name='retweeted_by', through='posts.Tweet_Retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
