# Generated by Django 4.2.4 on 2023-09-17 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tweet_retweets_tweet_retweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_Convo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply', to='posts.tweet')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='convo_tweet', to='posts.tweet')),
            ],
        ),
    ]
