# Generated by Django 4.2.4 on 2023-09-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_tweet_convo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_convo',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='posts.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet_convo',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo_tweet', to='posts.tweet'),
        ),
    ]
